#Mail Telemetry ver 0.2 Ansible Script.
#Developed from Marco Righini @ Intel (marco.righini@intel.com) .Thanks for the help to Josh Hilliker (josh.hilliker@intel.com).
-
   name: collectd_exporter Install
   hosts: all
   vars_files:
    - vars/vars.yaml
   tasks:

###########Yaml for server and collectd_exporter setup
# Create User
   - name: Add the user 'prometheus' with a specific uid and a primary group of 'admin'
     user:
      name: prometheus
      shell: /bin/bash
      comment:  Service

# Download Prometheus collectd_exporter Bits
   - name: Download collectd_exporter-0.2.0.linux-amd64.tar.gz
     get_url:
      url: https://github.com/prometheus/collectd_exporter/releases/download/0.2.0/collectd_exporter-0.2.0.linux-amd64.tar.gz
      dest: /home/prometheus/
      mode: 0660

# untar collectd_exporter bits to /home/prometheus/node_exporter
   - name: Extract collectd_exporter-0.2.0.linux-amd64.tar.gz into /home/prometheus/
     unarchive:
      src: /home/prometheus/collectd_exporter-0.2.0.linux-amd64.tar.gz
      dest: /home/prometheus/
      remote_src: yes

# Create /etc/systemd/system/collectd_exporter.service file if it does not exist
   - file:
       path: /etc/systemd/system/collectd_exporter.service
       state: touch
       mode: "u=rwx,g=rwx,o=rwx"
# Create collectd_exporter service
   - name: modify /etc/systemd/system/collectd_exporter.service
     blockinfile:
      path: /etc/systemd/system/collectd_exporter.service
      block: |
       [Unit]
       Description=Collectd Exporter
       Wants=network-online.target
       After=network-online.target
       After=collectd.service
       Requires=collectd.service

       [Service]
       User=prometheus
       ExecStart=/home/prometheus/collectd_exporter --collectd.listen-address=0.0.0.0:25826
       Restart=on-failure
       Type=simple

       [Install]
       WantedBy=default.target
# Now reload the systemd system
   - name: just force systemd to reread configs (2.4 and above)
     systemd:
      daemon_reload: yes

# Start collectd_exporter service
   - name: start service collectd_exporter
     service:
      name: collectd_exporter
      state: started

# Enabble collectd_exporter into SystemV services
   - name: enable service collectd_exporter and ensure it is not masked
     systemd:
      name: collectd_exporter
      enabled: yes
      masked: no
# Open collectd_exporter firewall ports 25826
   - name: open collectd_exporter  port
     firewalld:
       port=25826/udp
       zone=public
       permanent=true
       state=enabled
       immediate=yes
# Open collectd_exporter firewall ports 25826
   - name: open collectd_exporter  port
     firewalld:
       port=9103/tcp
       zone=public
       permanent=true
       state=enabled
       immediate=yes
