#Mail Telemetry ver 0.2 Ansible Script.
#Developed from Marco Righini @ Intel (marco.righini@intel.com) .Thanks for the help to Josh Hilliker (josh.hilliker@intel.com).
-
   name: Node_exporter Install
   hosts: all
   vars_files:
    - vars/vars.yaml
   tasks:

###########Yaml for server and node_exporter setup
#### from https://www.howtoforge.com/tutorial/how-to-install-prometheus-and-node-exporter-on-centos-7/
# Create User
   - name: Add the user 'prometheus' with a specific uid and a primary group of 'admin'
     user:
      name: prometheus
      shell: /bin/bash
      comment: Prometheus Service

# Download Prometheus node_exporter Bits
   - name: Download node_exporter-0.16.0-rc.1.linux-amd64.tar.gz
     get_url:
      url: https://github.com/prometheus/node_exporter/releases/download/v0.16.0-rc.1/node_exporter-0.16.0-rc.1.linux-amd64.tar.gz
      dest: /home/prometheus/
      mode: 0660

# untar node_exporter bits to /home/prometheus/node_exporter
   - name: Extract node_exporter-0.16.0-rc.1.linux-amd64.tar.gz into /home/prometheus/
     unarchive:
      src: /home/prometheus/node_exporter-0.16.0-rc.1.linux-amd64.tar.gz
      dest: /home/prometheus/
      remote_src: yes

# Rename directory
   - name: Rename node_exporter-0.16.0-rc.1.linux-amd64 DIRECTORY to node_exporter DIRECTORY
     command: mv /home/prometheus/node_exporter-0.16.0-rc.1.linux-amd64 /home/prometheus/node_exporter
# Create /etc/systemd/system/node_exporter.service file if it does not exist
   - file:
       path: /etc/systemd/system/node_exporter.service
       state: touch
       mode: "u=rwx,g=rwx,o=rwx"
# Before 2.3, option 'dest' or 'name' was used instead of 'path'
   - name: modify /etc/systemd/system/node_exporter.service
     blockinfile:
      path: /etc/systemd/system/node_exporter.service
      block: |
       [Unit]
       Description=Node Exporter
       Wants=network-online.target
       After=network-online.target

       [Service]
       User=prometheus
       ExecStart=/home/prometheus/node_exporter/node_exporter

       [Install]
       WantedBy=default.target
# Now reload the systemd system
   - name: just force systemd to reread configs (2.4 and above)
     systemd:
      daemon_reload: yes

# Start node_exporter service
   - name: start service node_exporter
     service:
      name: node_exporter
      state: started

# Enabble node_exporter into SystemV services
   - name: enable service node_exporter and ensure it is not masked
     systemd:
      name: node_exporter
      enabled: yes
      masked: no
# Open prometheus firewall ports
   - name: open node_exporter  port
     firewalld: port=9100/tcp zone=public permanent=true state=enabled immediate=yes
# Insert checks on services
# Check if Collectd exporter service is running
   - name: "Check if {{ prometheus_srv }} Server is responding to Collectd exporter service."
     uri:
      url: http://{{ prometheus_srv }}:9100/metrics
      status_code: 200
# Check if Collectd exporter service is running
   - name: "Check if {{ grafana_srv }} Server is responding to Collectd exporter service."
     uri:
      url: http://{{ grafana_srv }}:9100/metrics
      method: GET
      status_code: 200
# Check if Collectd exporter service is running
   - name: "Check if {{ monitored_ip01 }} Server is responding to Collectd exporter service."
     uri:
      url: http://{{ monitored_ip01 }}:9100/metrics
      method: GET
      status_code: 200
# Check if Collectd exporter service is running
   - name: "Check if {{ monitored_ip02 }} Server is responding to Collectd exporter service."
     uri:
      url: http://{{ monitored_ip02 }}:9100/metrics
      method: GET
      status_code: 200
# Check if Collectd exporter service is running
   - name: "Check if {{ monitored_ip03 }} Server is responding to Collectd exporter service."
     uri:
      url: http://{{ monitored_ip03 }}:9100/metrics
      method: GET
      status_code: 200
